classdef TestSignalContracts < matlab.unittest.TestCase
    %TestSignalContracts Verifies the frozen Simulink signal contract.

    properties
        DictionaryPath
    end

    methods (TestClassSetup)
        function addProjectPaths(testCase)
            projectRoot = fileparts(fileparts(mfilename('fullpath')));
            scriptsPath = fullfile(projectRoot, 'scripts');
            configPath = fullfile(projectRoot, 'config');
            sourcePath = fullfile(projectRoot, 'src');
            testCase.applyFixture( ...
                matlab.unittest.fixtures.PathFixture(scriptsPath));
            testCase.applyFixture( ...
                matlab.unittest.fixtures.PathFixture(configPath));
            testCase.applyFixture( ...
                matlab.unittest.fixtures.PathFixture(sourcePath));
        end
    end

    methods (TestMethodSetup)
        function createTemporaryDictionaryPath(testCase)
            temporaryFolder = tempname;
            mkdir(temporaryFolder);
            testCase.DictionaryPath = fullfile(temporaryFolder, ...
                'signal_contracts.sldd');
            testCase.addTeardown(@() rmdir(temporaryFolder, 's'));
        end
    end

    methods (Test)
        function testDictionaryGeneratorIsAvailable(testCase)
            projectRoot = fileparts(fileparts(mfilename('fullpath')));
            generatorPath = fullfile(projectRoot, 'scripts', ...
                'create_tmpsim_dictionary.m');

            testCase.verifyEqual(exist(generatorPath, 'file'), 2);
        end

        function testDictionaryGeneratorAcceptsDictionaryPath(testCase)
            testCase.verifyGreaterThanOrEqual( ...
                nargin(@create_tmpsim_dictionary), 1);
        end

        function testGeneratorCreatesEightFrozenBuses(testCase)
            create_tmpsim_dictionary(testCase.DictionaryPath);
            dictionary = Simulink.data.dictionary.open(testCase.DictionaryPath);
            testCase.addTeardown(@() close(dictionary));
            designData = getSection(dictionary, 'Design Data');
            entries = find(designData);

            actualNames = sort({entries.Name});
            expectedNames = sort({'RefBus', 'MeasBus', 'ErrBus', ...
                'HistoryBus', 'RiskRawBus', 'RiskBus', 'MPCParamBus', ...
                'CmdBus'});

            testCase.verifyEqual(actualNames, expectedNames);
        end

        function testMeasBusMatchesCarSimContract(testCase)
            create_tmpsim_dictionary(testCase.DictionaryPath);
            dictionary = Simulink.data.dictionary.open(testCase.DictionaryPath);
            testCase.addTeardown(@() close(dictionary));
            designData = getSection(dictionary, 'Design Data');
            measBus = getValue(getEntry(designData, 'MeasBus'));

            testCase.verifyEqual({measBus.Elements.Name}, { ...
                'x', 'y', 'yaw', 'vx', 'vy', 'yaw_rate', 'beta', ...
                'ay', 'delta_meas', 'ax_meas', 'delta_rate_meas', ...
                'meas_valid'});
            testCase.verifyEqual({measBus.Elements.DataType}, { ...
                'double', 'double', 'double', 'double', 'double', ...
                'double', 'double', 'double', 'double', 'double', ...
                'double', 'boolean'});
            testCase.verifyEqual({measBus.Elements.Unit}, { ...
                'm', 'm', 'rad', 'm/s', 'm/s', 'rad/s', 'rad', ...
                'm/s^2', 'rad', 'm/s^2', 'rad/s', ''});
        end

        function testRemainingBusesMatchFrozenContracts(testCase)
            create_tmpsim_dictionary(testCase.DictionaryPath);
            dictionary = Simulink.data.dictionary.open(testCase.DictionaryPath);
            testCase.addTeardown(@() close(dictionary));
            designData = getSection(dictionary, 'Design Data');

            verifyBus(testCase, designData, 'RefBus', { ...
                'x_ref', 'double', 1, 'm'; ...
                'y_ref', 'double', 1, 'm'; ...
                'psi_ref', 'double', 1, 'rad'; ...
                'kappa_ref', 'double', 1, '1/m'; ...
                'v_ref_base', 'double', 1, 'm/s'; ...
                'path_idx', 'uint32', 1, ''; ...
                'ref_valid', 'boolean', 1, ''});
            verifyBus(testCase, designData, 'ErrBus', { ...
                'e_y', 'double', 1, 'm'; ...
                'e_psi', 'double', 1, 'rad'; ...
                'e_y_rate', 'double', 1, 'm/s'; ...
                'e_psi_rate', 'double', 1, 'rad/s'; ...
                'yaw_ref', 'double', 1, 'rad'; ...
                'kappa_ref', 'double', 1, '1/m'; ...
                'v_ref_base', 'double', 1, 'm/s'; ...
                'err_valid', 'boolean', 1, ''});
            verifyBus(testCase, designData, 'HistoryBus', { ...
                'window', 'double', [16 14], ''; ...
                'latest_feature', 'double', [1 14], ''; ...
                'window_ready', 'boolean', 1, ''; ...
                'history_len', 'uint16', 1, ''; ...
                'sample_time', 'double', 1, 's'});
            verifyBus(testCase, designData, 'RiskRawBus', { ...
                'r_low_raw', 'double', 1, ''; ...
                'r_ey_raw', 'double', 1, ''; ...
                'r_stab_raw', 'double', 1, ''; ...
                'k_v_raw', 'double', 1, ''; ...
                'risk_raw_valid', 'boolean', 1, ''; ...
                'risk_source_id', 'uint8', 1, ''; ...
                'transformer_status_code', 'uint8', 1, ''; ...
                'transformer_latency_ms', 'double', 1, 'ms'});
            verifyBus(testCase, designData, 'RiskBus', { ...
                'r_low', 'double', 1, ''; ...
                'r_ey', 'double', 1, ''; ...
                'r_stab', 'double', 1, ''; ...
                'k_v', 'double', 1, ''; ...
                'risk_valid', 'boolean', 1, ''; ...
                'degraded_mode', 'boolean', 1, ''; ...
                'risk_source_id', 'uint8', 1, ''});
            verifyBus(testCase, designData, 'MPCParamBus', { ...
                'q_y', 'double', 1, ''; ...
                'q_psi', 'double', 1, ''; ...
                'q_beta', 'double', 1, ''; ...
                'q_r', 'double', 1, ''; ...
                'r_delta', 'double', 1, ''; ...
                'r_d_delta', 'double', 1, ''; ...
                'beta_max', 'double', 1, 'rad'; ...
                'yaw_rate_max', 'double', 1, 'rad/s'; ...
                'ay_max', 'double', 1, 'm/s^2'; ...
                'delta_max', 'double', 1, 'rad'; ...
                'delta_rate_max', 'double', 1, 'rad/s'; ...
                'v_ref_adapt', 'double', 1, 'm/s'; ...
                'param_valid', 'boolean', 1, ''});
            verifyBus(testCase, designData, 'CmdBus', { ...
                'delta_cmd', 'double', 1, 'rad'; ...
                'ax_cmd', 'double', 1, 'm/s^2'; ...
                'cmd_valid', 'boolean', 1, ''; ...
                'hold_last_cmd', 'boolean', 1, ''; ...
                'control_mode_id', 'uint8', 1, ''});
        end

        function testTmpsimConfigFreezesP0Contract(testCase)
            cfg = tmpsim_config();

            testCase.verifyEqual(cfg.sample.Ts_mpc, 0.02, AbsTol=1e-12);
            testCase.verifyEqual(cfg.sample.Ts_tr, 0.10, AbsTol=1e-12);
            testCase.verifyEqual(cfg.history.L, 16);
            testCase.verifyEqual(cfg.history.n_feature, 14);
            testCase.verifyEqual(cfg.feature_order, [ ...
                "vx", "vy", "yaw_rate", "ay", "beta", "delta_meas", ...
                "delta_rate_meas", "ax_meas", "e_y", "e_psi", ...
                "e_y_rate", "e_psi_rate", "kappa_ref", "v_ref_base"]);
            testCase.verifyEqual(cfg.mpc.Np, 15);
            testCase.verifyEqual(cfg.mpc.Nc, 5);
            testCase.verifyEqual(cfg.environment.matlab_release, "R2024b");
            testCase.verifyEqual(cfg.environment.carsim_version, "2019.1");
            testCase.verifyEqual(cfg.convention.delta_positive, "left");
            testCase.verifyEqual(cfg.convention.yaw_positive, "left");
            testCase.verifyEqual(cfg.convention.ay_positive, "left");
        end

        function testVehicleParametersMatchCClassEvidence(testCase)
            vehicle = vehicle_params();

            testCase.verifyEqual(vehicle.mass, 1501.0, AbsTol=1e-12);
            testCase.verifyEqual(vehicle.Iz, 2192.089539, AbsTol=1e-9);
            testCase.verifyEqual(vehicle.wheelbase, 2.910, AbsTol=1e-12);
            testCase.verifyEqual(vehicle.lf, 1.049562958, AbsTol=1e-9);
            testCase.verifyEqual(vehicle.lr, 1.860437042, AbsTol=1e-9);
            testCase.verifyEqual(vehicle.Cf, 159055.11037704, AbsTol=1e-6);
            testCase.verifyEqual(vehicle.Cr, 92776.4754843415, AbsTol=1e-6);
            testCase.verifyEqual(vehicle.source.dataset, "C-Class, Hatchback");
            testCase.verifyEqual(vehicle.source.evidence_run, "day2_export_smoke");
            testCase.verifyEqual(vehicle.tire.linearization, ...
                "small_slip_0p5_deg_at_static_load");
        end

        function testConfigValidationAcceptsFrozenP0Config(testCase)
            cfg = tmpsim_config();

            testCase.verifyWarningFree( ...
                @() tmpsim.validateOnlineConfig(cfg));
        end

        function testConfigValidationRejectsNonIntegerTransformerRate(testCase)
            cfg = tmpsim_config();
            cfg.sample.Ts_tr = 0.07;

            testCase.verifyError( ...
                @() tmpsim.validateOnlineConfig(cfg), ...
                'tmpsim:InvalidSampleRateRatio');
        end

        function testConfigValidationRejectsUnexpectedFeatureOrder(testCase)
            cfg = tmpsim_config();
            cfg.feature_order(1) = "vy";

            testCase.verifyError( ...
                @() tmpsim.validateOnlineConfig(cfg), ...
                'tmpsim:InvalidFeatureOrder');
        end

        function testConfigValidationRejectsInvalidFeatureStatistics(testCase)
            cfg = tmpsim_config();
            featureStats.mean_train = zeros(1, 14);
            featureStats.std_train = [0 ones(1, 13)];
            featureStats.feature_order = cfg.feature_order;

            testCase.verifyError( ...
                @() tmpsim.validateOnlineConfig(cfg, featureStats), ...
                'tmpsim:InvalidFeatureStatsValues');
        end
    end
end

function verifyBus(testCase, designData, busName, expectedSpecs)
bus = getValue(getEntry(designData, busName));
elements = bus.Elements;

testCase.verifyEqual({elements.Name}, expectedSpecs(:, 1).');
testCase.verifyEqual({elements.DataType}, expectedSpecs(:, 2).');
testCase.verifyEqual([elements.Dimensions], [expectedSpecs{:, 3}]);
testCase.verifyEqual({elements.Unit}, expectedSpecs(:, 4).');
end
